# Generated by Django 5.0.1 on 2024-01-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationconfig',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
