# Generated by Django 5.0.1 on 2024-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message', models.CharField(max_length=255)),
                ('create_date', models.DateField()),
                ('create_hour', models.TimeField()),
                ('is_lock', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_text', models.CharField(max_length=255)),
                ('notification_date', models.DateField()),
                ('notification_time', models.TimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField()),
                ('create_hour', models.TimeField()),
                ('last_modification', models.DateField()),
                ('last_modification_hour', models.TimeField()),
                ('close_date', models.DateField(blank=True, null=True)),
                ('close_hour', models.TimeField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
