# Generated by Django 5.0.1 on 2024-01-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contact_number',
        ),
    ]
