# Generated by Django 5.0.1 on 2024-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_notification_task_id_notification_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='task',
            new_name='task_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
