# Generated by Django 5.0.1 on 2024-05-15 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_file_file_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recently_viewed_tasks_id', models.ManyToManyField(related_name='recently_viewed', to='tasks.task')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
