# Generated by Django 5.0.1 on 2024-05-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_recentlyviewedtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewedtasks',
            name='recently_viewed_tasks_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='recently_viewed', to='tasks.task'),
        ),
    ]
