# Generated by Django 5.0.1 on 2024-07-04 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_phrase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='phrase',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
