# Generated by Django 5.0.1 on 2024-07-04 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_phrase_update_date_alter_phrase_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
