# Generated by Django 5.0.1 on 2024-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
