# Generated by Django 5.0.1 on 2024-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_options', '0002_taskoptions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoptions',
            name='advice',
            field=models.CharField(default='', max_length=100),
        ),
    ]
