# Generated by Django 5.0.1 on 2024-05-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_options', '0003_taskoptions_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskoptions',
            name='advice',
            field=models.CharField(default='', max_length=255),
        ),
    ]
